HouseTable<-read.table("C:/Course Work/Machine learning/Courseera/R/Course 4/household_power_consumption.txt",sep = ";",header = TRUE)
dim(HouseTable)
names(HouseTable)
library(dplyr)
tabfin<-filter(HouseTable,Date==("1/2/2007") | Date== "2/2/2007")
unique(tabfin$Date)
y<-strptime(paste(tabfin$Date,tabfin$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
x<-as.numeric(tabfin$Global_active_power)
png(file="C:/Course Work/Machine learning/Courseera/R/Course 4/Plot2.png")
plot(y,x,type = "l",ylab = "Global active power")
dev.off()